version: 1
update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: daily
    default_reviewers:
      - jbhannah
  - package_manager: submodules
    directory: /
    update_schedule: daily
    default_reviewers:
      - jbhannah
